// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "../Theme.bs.js";
import * as React from "react";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as ReactNative from "react-native";

function Box(Props) {
  var children = Props.children;
  var variantOpt = Props.variant;
  var alignOpt = Props.align;
  var justifyOpt = Props.justify;
  var flexOpt = Props.flex;
  var flexDirectionOpt = Props.flexDirection;
  var customStyleOpt = Props.customStyle;
  var variant = variantOpt !== undefined ? variantOpt : /* Default */0;
  var align = alignOpt !== undefined ? alignOpt : "flexStart";
  var justify = justifyOpt !== undefined ? justifyOpt : "flexStart";
  var flex = flexOpt !== undefined ? flexOpt : 1;
  var flexDirection = flexDirectionOpt !== undefined ? flexDirectionOpt : "column";
  var customStyle = customStyleOpt !== undefined ? Caml_option.valFromOption(customStyleOpt) : ({});
  var variantStyle;
  switch (variant) {
    case /* Default */0 :
        variantStyle = Theme.styles.defaultBox;
        break;
    case /* Container */1 :
        variantStyle = Theme.styles.container;
        break;
    case /* WithSpacing */2 :
        variantStyle = Theme.styles.defaultBoxWithSpacing;
        break;
    
  }
  return React.createElement(ReactNative.View, {
              style: [
                {
                  alignItems: (function () {
                        switch (align) {
                          case "flexStart" :
                              return "flex-start";
                          case "flexEnd" :
                              return "flex-end";
                          case "center" :
                              return "center";
                          case "stretch" :
                              return "stretch";
                          case "baseline" :
                              return "baseline";
                          
                        }
                      })(),
                  flex: flex,
                  flexDirection: (function () {
                        switch (flexDirection) {
                          case "row" :
                              return "row";
                          case "rowReverse" :
                              return "row-reverse";
                          case "column" :
                              return "column";
                          case "columnReverse" :
                              return "column-reverse";
                          
                        }
                      })(),
                  justifyContent: (function () {
                        switch (justify) {
                          case "flexStart" :
                              return "flex-start";
                          case "flexEnd" :
                              return "flex-end";
                          case "center" :
                              return "center";
                          case "spaceAround" :
                              return "space-around";
                          case "spaceBetween" :
                              return "space-between";
                          case "spaceEvenly" :
                              return "space-evenly";
                          
                        }
                      })()
                },
                variantStyle,
                customStyle
              ],
              children: children
            });
}

var make = Box;

export {
  make ,
  
}
/* Theme Not a pure module */
