// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.bs.js";
import * as React from "react";
import * as Spacer from "./components/Spacer.bs.js";
import * as ReactNative from "react-native";

function LoginScreen(Props) {
  return React.createElement(ReactNative.SafeAreaView, {
              style: Theme.styles.container,
              children: React.createElement(ReactNative.View, {
                    style: Theme.styles.container,
                    children: null
                  }, React.createElement(Spacer.make, {
                        size: /* Multiplier */{
                          _0: 10
                        }
                      }), React.createElement(ReactNative.Text, {
                        children: "Memociné 🍿",
                        style: Theme.styles.title
                      }), React.createElement(Spacer.make, {
                        size: /* Auto */0
                      }), React.createElement(ReactNative.Pressable, {
                        children: (function (pressed) {
                            return React.createElement(ReactNative.Text, {
                                        children: "Sign in",
                                        style: Theme.styles.buttonTxt
                                      });
                          }),
                        style: (function (pressed) {
                            return {
                                    backgroundColor: Theme.colors.main,
                                    flexDirection: "row"
                                  };
                          })
                      }))
            });
}

var make = LoginScreen;

export {
  make ,
  
}
/* Theme Not a pure module */
