// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.bs.js";
import * as React from "react";
import * as LoginScreen from "./LoginScreen.bs.js";
import * as RootContext from "./RootContext.bs.js";
import * as Stack$ReactNavigation from "rescript-react-navigation/src/Stack.bs.js";
import * as Native from "@react-navigation/native";
import * as BottomTabs$ReactNavigation from "rescript-react-navigation/src/BottomTabs.bs.js";

var M = {};

var include = BottomTabs$ReactNavigation.Make(M);

var $$Screen = include.$$Screen;

var $$Navigator = include.$$Navigator;

function RootNavigation$Tabs(Props) {
  return React.createElement($$Navigator.make, {
              initialRouteName: "feed",
              children: null
            }, React.createElement($$Screen.make, {
                  name: "home",
                  component: LoginScreen.make
                }), React.createElement($$Screen.make, {
                  name: "friends",
                  component: LoginScreen.make
                }), React.createElement($$Screen.make, {
                  name: "settings",
                  component: LoginScreen.make
                }));
}

var Tabs_Navigation = include.Navigation;

var Tabs_bottomTabs = include.bottomTabs;

var Tabs_ScreenWithCallback = include.ScreenWithCallback;

var Tabs = {
  Navigation: Tabs_Navigation,
  bottomTabs: Tabs_bottomTabs,
  $$Screen: $$Screen,
  ScreenWithCallback: Tabs_ScreenWithCallback,
  $$Navigator: $$Navigator,
  make: RootNavigation$Tabs
};

var include$1 = Stack$ReactNavigation.Make(M);

var $$Screen$1 = include$1.$$Screen;

var $$Navigator$1 = include$1.$$Navigator;

function RootNavigation$RootStack(Props) {
  var match = React.useContext(RootContext.context);
  return React.createElement(Native.NavigationContainer, {
              children: React.createElement($$Navigator$1.make, {
                    initialRouteName: "unauthorized",
                    children: match[0].authorized ? React.createElement(React.Fragment, undefined, React.createElement($$Screen$1.make, {
                                name: "authorized",
                                options: (function (props) {
                                    return {
                                            headerStyle: {
                                              backgroundColor: Theme.colors.bg,
                                              borderWidth: 0
                                            },
                                            title: ""
                                          };
                                  }),
                                component: RootNavigation$Tabs
                              }), React.createElement($$Screen$1.make, {
                                name: "settings",
                                options: (function (props) {
                                    return {
                                            animationEnabled: false,
                                            title: "s"
                                          };
                                  }),
                                component: LoginScreen.make
                              })) : React.createElement($$Screen$1.make, {
                            name: "unauthorized",
                            options: (function (props) {
                                return {
                                        headerShown: false
                                      };
                              }),
                            component: LoginScreen.make
                          })
                  })
            });
}

var RootStack_Navigation = include$1.Navigation;

var RootStack_HeaderTitle = include$1.HeaderTitle;

var RootStack_Header = include$1.Header;

var RootStack_stack = include$1.stack;

var RootStack_ScreenWithCallback = include$1.ScreenWithCallback;

var RootStack = {
  Navigation: RootStack_Navigation,
  HeaderTitle: RootStack_HeaderTitle,
  Header: RootStack_Header,
  stack: RootStack_stack,
  ScreenWithCallback: RootStack_ScreenWithCallback,
  $$Screen: $$Screen$1,
  $$Navigator: $$Navigator$1,
  make: RootNavigation$RootStack
};

export {
  M ,
  Tabs ,
  RootStack ,
  
}
/* include Not a pure module */
