// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var initState = {
  authorized: false,
  darkMode: false
};

function reducer(state, action) {
  if (action.TAG === /* SetDarkMode */0) {
    return {
            authorized: state.authorized,
            darkMode: action._0
          };
  } else {
    return {
            authorized: action._0,
            darkMode: state.darkMode
          };
  }
}

var context = React.createContext([
      initState,
      (function (param) {
          
        })
    ]);

var provider = context.Provider;

function RootContext$Provider(Props) {
  var children = Props.children;
  var reducer$1 = React.useReducer(reducer, initState);
  return React.createElement(provider, {
              value: reducer$1,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: RootContext$Provider
};

export {
  initState ,
  reducer ,
  context ,
  Provider ,
  
}
/* context Not a pure module */
