// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as RootContext from "./RootContext.bs.js";
import * as ReactNative from "react-native";
import * as RootNavigation from "./RootNavigation.bs.js";
import * as ApolloContainer from "./ApolloContainer.bs.js";

function Root$app(Props) {
  return React.createElement(ApolloContainer.make, {
              children: React.createElement(RootContext.Provider.make, {
                    children: null
                  }, React.createElement(RootNavigation.make, {}), React.createElement(ReactNative.StatusBar, {
                        barStyle: "default"
                      }))
            });
}

var app = Root$app;

export {
  app ,
  
}
/* react Not a pure module */
