// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

var styles = ReactNative.StyleSheet.create({
      flex: {
        flex: 1
      },
      container: {
        backgroundColor: "#1A1D2B",
        flex: 1,
        paddingHorizontal: 4 * 4
      },
      center: {
        alignItems: "center",
        justifyContent: "center"
      },
      title: {
        color: "#FFFFFF",
        fontSize: 48,
        fontWeight: "800"
      },
      subtitle: {
        color: "#FFFFFF",
        fontSize: 24,
        fontWeight: "500"
      },
      body: {
        color: "#FFFFFF",
        fontSize: 14,
        fontWeight: "500"
      },
      buttonTxt: {
        color: "#FFFFFF",
        fontSize: 18,
        fontWeight: "700"
      }
    });

var colors = {
  main: "#FDAC21",
  secondary: "#F6FF00",
  tertiary: "#34008F",
  bg: "#1A1D2B",
  title: "#FFFFFF",
  subtitle: "#FFFFFF",
  body: "#FFFFFF"
};

var baseMargin = 4;

var fontBase = 4;

export {
  colors ,
  baseMargin ,
  fontBase ,
  styles ,
  
}
/* styles Not a pure module */
